[build]
nilixable = false

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"

[env]
PORT = { default = "8000" }
CLOUDFLARE_API_TOKEN = { default = "TyCmFLgySVRZ5RFOvoXXq9gOKbl3HNHaXCp7YIKc" }
CLOUDFLARE_ACCOUNT_ID = { default = "bbd9ec5819a97651cc9f481c1c275c3d" }
TWILIO_ACCOUNT_SID = { default = "[REDACTED]" }
TWILIO_AUTH_TOKEN = { default = "e65397c32f16f83469ee9d859308eb6a" }
GHL_API_KEY = { default = "pit-fdf8bee7-9c21-4748-b265-e732781c8b3f" }
GHL_LOCATION_ID = { default = "PMgbQ375TEGOyGXsKz7e" }